name: "Spotify top 5 artists update"
description: "Update the top 5 artists table in your readme"
inputs:
  content:
    description: "Content of old readme"
    required: true
  token:
    description: "Refresh token from Spotify"
    required: true
  clientId:
    description: "Spotify app client id"
    required: true
  cliSecret:
    description: "Spotify app client secret"
    required: true
outputs:
  content:
    description: "The updated readme data"
runs:
  using: "node12"
  main: "dist/index.js"
